Add mp4 files support
Neca-development/Frenly_backend pull request #16
Opened 2022-12-14 15:57 UTC by AndreYurin

2022-12-14 15:59 UTC, AndreYurin commented
The link from ipfs did not give a png picture, but a video, which caused the video to be saved as a picture and crashing.
Tried to make uploading files more flexible

2022-12-15 05:59 UTC, VKirbyatev requested changes

2022-12-15 05:59 UTC, VKirbyatev commented on src/services/block-subscriber.service.ts
> +        if (data?.headers?.['content-type']) {
Можно переделать на просто data?.headers['content-type'] и добавь явную проверку на null
if (data?.headers['content-type'] != null)

2022-12-15 05:59 UTC, VKirbyatev commented on src/services/block-subscriber.service.ts
> +    const data = await axios.get(fileUrl, {
Если убираешь деструктор, то поменяй нейминг, этот обьект в таком случае будет response или axiosResponse называться

2022-12-15 05:59 UTC, VKirbyatev commented on src/services/block-subscriber.service.ts
> +            if ((dataFormats[0] === 'video' || dataFormats[1] === 'mp4' || dataFormats[1] === 'webp')
У тебя в if'е стоит проверка dataFormats[0] === 'video', а подставляешь ты в newFilePath всегда dataFormats[1], раздели проверку, либо убери ее.

2022-12-15 05:59 UTC, VKirbyatev commented on src/services/block-subscriber.service.ts
> +          try {
У тебя в try-catch блоке нету тровающих операций. Можно его убрать при желании. Но точно можно убрать BadRequestException - это HTTP ошибка для контроллеров, а тут у тебя бэкграунд-операция, тут не может быть bad request'a

2022-12-15 05:59 UTC, VKirbyatev commented on src/services/block-subscriber.service.ts
> +            const finalExt = await this.downloadFile(data.imageURI, `${FilePaths.TOKEN_IMAGES}/${image}`);
Сделай тогда, чтобы имя файлу подставлялось внутри функции downloadFile и возвращай это имя, а отсюда убери проверку на .png.

2022-12-15 12:17 UTC, VKirbyatev approved these changes

2022-12-15 12:19 UTC, merged